#!/usr/bin/env python

from sys import stdin, argv
from bs4 import BeautifulSoup

if argv[1] == "-h":
    help = """Usage:
    tagextract {tag type} {tag property} {property value} {file}
    """
    print(help)
else:
    f = stdin if len(argv) < 5 else open(argv[4])
    h = BeautifulSoup(f.read(), 'lxml')
    tag_content = h.find(argv[1], attrs={argv[2]: argv[3]}).encode_contents(
        encoding='utf-8', formatter='minimal').decode(('utf-8'))
    print(tag_content)
