# this was used for a multi-region deployment where Dev has one region, and
# staging/prod have two. "item" is mandatory, and we do stages looping over
# the combined list of "item" followed by the items in "list"

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

parameters:
- name: item
  default: first
- name: list
  type: object
  default:
    - second
    - third

stages:
- ${{ each i in split(format('{0};{1}', parameters.item, join(';',parameters.list) ), ';') }}:
  - ${{ if ne(i,'') }}:
    - stage:
      displayName: ${{i}}
      jobs:
      - job:
        displayName: ${{i}}
        steps:
        - bash: echo "${{ i }}"
